//! Chat sessions and tail reads on the real LFM2.5-8B-A1B (`crate::chat_session`
//! has the design). What this certifies, on one backend:
//!
//! - a turn leaves a chain of checkpoints whose ids are exactly the previous
//!   checkpoint's plus the rendered turns plus the generated ids (never a
//!   re-tokenization of generated text), and the turn's split text
//!   re-renders to its generated bytes;
//! - the canonical schedule: a checkpoint reached by starting a chat with
//!   turns A and B and one reached by continuing after A with B are the
//!   same state, bit for bit (checked through a tail read on each, in two
//!   daemons);
//! - a repeated read from a checkpoint is identical, and a chat turn with
//!   reads (a plain one and a tail read of its own fresh checkpoint)
//!   served at its pauses generates what it generates alone, and each read
//!   answers what it answers alone;
//! - an unknown checkpoint is a 404-class refusal, not a rebuild.
//!
//! And it MEASURES, rather than asserts, how far a read resumed from a
//! checkpoint sits from a cold read of the same bytes (`use_cache: false`):
//! chunk schedules change the numbers, so the two are not expected to agree.
//!
//! Ignored by default: it loads and hashes the 6 GB GGUF twice.
//! `tests/support` names the GPU (never cpu or auto), bounds the context and
//! arms the host-memory guard. Under the zorak-heavy lock:
//!
//!   LFM2_MODELS_DIR=... flock ~/.cache/zorak-heavy.lock cargo test -p lfm2d \
//!     --release --features rocm --test chat_real -- --ignored --test-threads=1 --nocapture
mod support;
use lfm2d::adjudicator::{Adjudicator, Failure, Generator, YieldPoint};
use lfm2d::chat::{AFTER_EOS, GENERATION_PROMPT, Message};
use lfm2d::chat_session::{ChatRequest, ChatResponse, checkpoint_id};
use lfm2d::config::Cli;
use lfm2d::opinion_api::OpinionRequest;
use serde_json::{Value, json};
use std::cell::{Cell, RefCell};

const SPEC: &str = "email-triage-v1";
const SYSTEM: &str = "You are a helpful assistant for Dana, who runs customer support for a small \
                      online kitchenware store. Help her work through her inbox. Be concise.";
const A: &str = "Morning! Someone asks whether our enameled dutch oven works on induction. It does. \
                 Draft a one-line reply?";
const B: &str = "Thanks. Next one is angrier, I'll paste it in a second.";
const B2: &str = "Actually, before you answer: keep it under ten words.";
const EMAILS: [&str; 2] = [
    "hi, can you tell me if my order 8812 shipped yet? the tracking page just says label created",
    "I was charged twice for my March invoice and nobody has answered my last two emails. I want the \
     duplicate refunded today.",
];

fn cli() -> Cli {
    support::adjudicator_cli(&[SPEC])
}

fn start(messages: &[&str], max_tokens: usize) -> ChatRequest {
    let messages: Vec<Value> = messages.iter().map(|m| json!({"role": "user", "content": m})).collect();
    serde_json::from_value(json!({"system": SYSTEM, "messages": messages, "max_tokens": max_tokens})).unwrap()
}

fn cont(from: &str, message: &str, max_tokens: usize) -> ChatRequest {
    serde_json::from_value(json!({
        "from": from, "messages": [{"role": "user", "content": message}], "max_tokens": max_tokens
    }))
    .unwrap()
}

fn chat(adjudicator: &mut Adjudicator, request: &ChatRequest) -> ChatResponse {
    adjudicator.chat(request, &|_| {}, &|| Ok(())).expect("chat")
}

fn read_request(checkpoint: Option<&str>, email: &str, use_cache: bool) -> OpinionRequest {
    serde_json::from_value(json!({
        "spec": SPEC,
        "context": checkpoint.map(|c| json!({"checkpoint": c})),
        "state": {"input": email},
        "questions": [{"field": "feeling"}, {"field": "verdict"}],
        "use_cache": use_cache,
    }))
    .unwrap()
}

/// A read's load-bearing numbers: what it described and scored, and the
/// bytes it read. Never timings or cache outcomes.
fn read(adjudicator: &mut Adjudicator, request: &OpinionRequest) -> Result<Value, Failure> {
    let menu = adjudicator.menu();
    let entry = menu.iter().find(|e| e.spec == SPEC).unwrap();
    let questions = entry.resolve_all(&request.questions).unwrap();
    let r = adjudicator.opine(request, &questions, &|| Ok(()))?;
    Ok(json!({
        "described": r.described,
        "answers": r.answers,
        "prompt_tokens": r.prompt_tokens,
        "context": r.context,
    }))
}

fn encode(tokenizer: &tokenizers::Tokenizer, text: &str) -> Vec<u32> {
    tokenizer.encode(text, false).unwrap().get_ids().to_vec()
}

/// Runs `reads[i]` at pause `at[i]` of whatever job it is handed to.
struct AtPauses {
    plan: Vec<(usize, OpinionRequest)>,
    pauses: Cell<usize>,
    served: RefCell<Vec<Value>>,
}
impl YieldPoint<Adjudicator> for AtPauses {
    fn check(&self) -> Result<(), Failure> {
        Ok(())
    }
    fn pause(&self, adjudicator: &mut Adjudicator) -> Result<(), Failure> {
        let n = self.pauses.get();
        self.pauses.set(n + 1);
        for (at, request) in &self.plan {
            if *at == n {
                let numbers = read(adjudicator, request).expect("a read at a pause");
                self.served.borrow_mut().push(numbers);
            }
        }
        Ok(())
    }
}

/// `|Δ|` between two reads' option logprobs, per option, and whether the
/// descriptions (the generated text before each slot) came out the same.
fn drift(a: &Value, b: &Value) -> (Vec<f64>, bool) {
    let mut gaps = Vec::new();
    for (x, y) in a["answers"].as_array().unwrap().iter().zip(b["answers"].as_array().unwrap()) {
        for (o, p) in x["options"].as_array().unwrap().iter().zip(y["options"].as_array().unwrap()) {
            assert_eq!(o["option"], p["option"]);
            gaps.push((o["logprob"].as_f64().unwrap() - p["logprob"].as_f64().unwrap()).abs());
        }
    }
    (gaps, a["described"] == b["described"])
}

#[test]
#[ignore = "loads and hashes the 6 GB LFM2.5-8B-A1B GGUF twice; minutes on a GPU host"]
fn chat_checkpoints_and_tail_reads_on_the_real_model() {
    let mut a1 = support::load_adjudicator(&cli());
    let tokenizer = a1.tokenizer_clone();
    let eos = tokenizer.token_to_id("<|im_end|>").unwrap();

    // 1. A turn, and the chain it leaves.
    let r1 = chat(&mut a1, &start(&[A], 1024));
    assert_eq!(r1.finish_reason, "stop", "{:?}", r1.text);
    let user1 = a1.chat_checkpoint_ids(&r1.checkpoint_user).expect("held");
    let head = lfm2d::chat::render_head(SYSTEM, &[]).unwrap();
    let turn_a = Message::User { content: A.into() }.render().unwrap();
    assert_eq!(user1, [encode(&tokenizer, &head), encode(&tokenizer, &turn_a)].concat());
    assert_eq!(r1.checkpoint_user, checkpoint_id(&user1));
    let asst1_id = r1.checkpoint.clone().expect("a finished turn leaves a checkpoint");
    let asst1 = a1.chat_checkpoint_ids(&asst1_id).expect("held");
    assert_eq!(asst1_id, checkpoint_id(&asst1));
    let opening = encode(&tokenizer, GENERATION_PROMPT);
    let after = encode(&tokenizer, AFTER_EOS);
    assert!(asst1.starts_with(&[user1.clone(), opening.clone()].concat()));
    assert!(asst1.ends_with(&[&[eos][..], &after].concat()));
    assert_eq!(asst1.len(), user1.len() + opening.len() + r1.completion_tokens + after.len());
    assert_eq!(Some(r1.checkpoint_tokens.unwrap()), Some(asst1.len()));
    // The split text re-renders to exactly the generated bytes. Only a
    // closed region has a rendering; this turn must close one for the check
    // to mean anything.
    assert!(r1.text.starts_with("<think>") && r1.text.contains("</think>"), "{:?}", r1.text);
    let rerendered = Message::Assistant {
        thinking: r1.thinking.clone(),
        content: r1.content.clone(),
        tool_calls: None,
    }
    .render()
    .unwrap();
    assert_eq!(tokenizer.decode(&asst1[user1.len()..], false).unwrap(), rerendered);
    eprintln!(
        "turn 1: {} prompt tokens, {} generated, thinking {} chars, content {:?}",
        r1.prompt_tokens,
        r1.completion_tokens,
        r1.thinking.as_deref().map_or(0, str::len),
        r1.content
    );

    // 2. Continuing grows the chain by exactly the appended turn.
    let r2 = chat(&mut a1, &cont(&asst1_id, B, 1));
    let user2 = a1.chat_checkpoint_ids(&r2.checkpoint_user).unwrap();
    let turn_b = Message::User { content: B.into() }.render().unwrap();
    assert_eq!(user2, [asst1.clone(), encode(&tokenizer, &turn_b)].concat());
    assert_eq!(r2.cached_tokens, asst1.len());
    assert_eq!((r2.finish_reason.as_str(), r2.checkpoint.as_deref()), ("length", None), "a cut turn leaves no checkpoint");

    // 3. Repeating a turn is served from its held user checkpoint, and
    //    generates the same.
    let r1b = chat(&mut a1, &start(&[A], 1024));
    assert_eq!(r1b.cached_tokens, r1b.prompt_tokens);
    assert_eq!((&r1b.text, &r1b.checkpoint), (&r1.text, &r1.checkpoint));

    // 4. Two turns in a row by continuing: after A (no reply), then B2.
    let r3 = chat(&mut a1, &cont(&r1.checkpoint_user, B2, 1));
    let tail3 = r3.checkpoint_user.clone();

    // 5. Tail reads: repeated, cold, unknown.
    let mut resumed = Vec::new();
    let mut cold = Vec::new();
    for checkpoint in [&r1.checkpoint_user, &asst1_id, &r2.checkpoint_user, &tail3] {
        for email in EMAILS {
            let first = read(&mut a1, &read_request(Some(checkpoint), email, true)).unwrap();
            let again = read(&mut a1, &read_request(Some(checkpoint), email, true)).unwrap();
            assert_eq!(first, again, "a repeated read from one checkpoint is identical");
            assert_eq!(first["context"]["checkpoint"], checkpoint.as_str());
            resumed.push(first);
            cold.push(read(&mut a1, &read_request(Some(checkpoint), email, false)).unwrap());
        }
    }
    {
        // An input not read yet: a described miss resumes at the checkpoint.
        let request = read_request(Some(&tail3), "Where is my parcel? Tracking has not moved in a week.", true);
        let menu = a1.menu();
        let questions = menu.iter().find(|e| e.spec == SPEC).unwrap().resolve_all(&request.questions).unwrap();
        let r = a1.opine(&request, &questions, &|| Ok(())).unwrap();
        assert_eq!(r.cache.prefix, "checkpoint", "a tail read never uses the spec's own prefix");
        assert_eq!(r.cached_tokens, a1.chat_checkpoint_ids(&tail3).unwrap().len());
    }
    let unknown = read(&mut a1, &read_request(Some(&"0".repeat(64)), EMAILS[0], true)).unwrap_err();
    assert!(matches!(unknown, Failure::NotFound(_)), "{unknown:?}");
    // A plain read (the spec's own prompt) of the first email, and the tail
    // reads of turn 1's user checkpoint, for step 7.
    let plain_alone = read(&mut a1, &read_request(None, EMAILS[0], false)).unwrap();
    let tail_alone = resumed[0].clone();
    let tail3_alone = resumed[6].clone();

    // The drift, measured: resumed vs cold over the same bytes.
    let mut all = Vec::new();
    let mut same_description = 0;
    for (r, c) in resumed.iter().zip(&cold) {
        let (gaps, same) = drift(r, c);
        all.extend(gaps);
        same_description += same as usize;
    }
    all.sort_by(f64::total_cmp);
    eprintln!(
        "resumed vs cold tail reads: n={} reads, {} option logprobs; same description {}/{}; \
         |Δ logprob| p50 {:.4} p90 {:.4} max {:.4} nats",
        resumed.len(),
        all.len(),
        same_description,
        resumed.len(),
        all[all.len() / 2],
        all[all.len() * 9 / 10],
        all[all.len() - 1]
    );
    for (i, (r, c)) in resumed.iter().zip(&cold).enumerate() {
        let top = |v: &Value| -> Vec<(String, f64)> {
            v["answers"]
                .as_array()
                .unwrap()
                .iter()
                .map(|a| {
                    let best = a["options"]
                        .as_array()
                        .unwrap()
                        .iter()
                        .max_by(|x, y| x["prob"].as_f64().unwrap().total_cmp(&y["prob"].as_f64().unwrap()))
                        .unwrap();
                    (best["option"].as_str().unwrap().to_string(), a["sequence_mass"].as_f64().unwrap())
                })
                .collect()
        };
        eprintln!("  read {i}: resumed {:?} cold {:?}", top(r), top(c));
    }
    drop(a1);

    // 6. The canonical schedule: a fresh daemon STARTS a chat with A and B2
    //    and lands on the same checkpoint, whose read is bit-identical.
    let mut a2 = support::load_adjudicator(&cli());
    let r3b = chat(&mut a2, &start(&[A, B2], 1));
    assert_eq!(r3b.checkpoint_user, tail3, "same ids, same id");
    assert_eq!(r3b.cached_tokens, 0, "a fresh store: computed, not held");
    assert_eq!(
        read(&mut a2, &read_request(Some(&tail3), EMAILS[0], true)).unwrap(),
        tail3_alone,
        "started [A, B2] and continued A then B2 are the same state"
    );

    // 7. Reads at a chat turn's pauses: a plain read during the prefill, a
    //    tail read of the turn's own fresh user checkpoint during decode.
    //    The turn generates what it generated alone (in the other daemon),
    //    and each read answers what it answered alone.
    let at = AtPauses {
        plan: vec![
            (0, read_request(None, EMAILS[0], false)),
            (6, read_request(Some(&r1.checkpoint_user), EMAILS[0], true)),
        ],
        pauses: Cell::new(0),
        served: RefCell::new(Vec::new()),
    };
    let r1c = a2.chat(&start(&[A], 1024), &|_| {}, &at).expect("chat with reads at its pauses");
    assert_eq!(at.served.borrow().len(), 2);
    assert_eq!((&r1c.text, &r1c.checkpoint), (&r1.text, &r1.checkpoint), "the turn does not move");
    assert_eq!(at.served.borrow()[0], plain_alone, "a plain read at a prefill pause");
    assert_eq!(at.served.borrow()[1], tail_alone, "a tail read of the paused turn's own checkpoint");
    // And the checkpoint the read forked is undisturbed by it: the next
    // turn from there is still the chain the first daemon built.
    let r2c = chat(&mut a2, &cont(r1c.checkpoint.as_ref().unwrap(), B, 1));
    assert_eq!(r2c.checkpoint_user, r2.checkpoint_user);
}

/// A budget that cannot hold a turn's two checkpoints at the full context
/// stops the daemon at startup, naming the flag.
#[test]
#[ignore = "loads and hashes the 6 GB LFM2.5-8B-A1B GGUF; minutes on a GPU host"]
fn a_budget_too_small_for_one_turn_refuses_to_start() {
    let mut cli = cli();
    cli.chat_checkpoint_budget_mib = 1;
    let err = support::try_load_adjudicator(&cli).err().expect("1 MiB cannot hold a turn's two checkpoints");
    assert!(err.contains("--chat-checkpoint-budget-mib"), "{err}");
}
